created a header and navBar, connected it to the backend
WildCodeSchool/2103-lille-js-p3-edtech-frontend pull request #2
Opened 2021-06-02 19:53 UTC by Hacene010

2021-06-02 20:23 UTC, GeorgesFORTRY submitted a review, later dismissed
all is ok !

2021-06-03 06:05 UTC, LoicBrassart requested changes
One more thing to fix!

2021-06-03 06:05 UTC, LoicBrassart commented on src/components/Header/Header.jsx
> +    axios.get('http://localhost:8080/texts').then(({ data }) => {
You shouldn't use a hardcoded "http://localhost:8080" value: once in production, it won't work anymore.
Create a `.env` in your frontend folder and move this value there, same as the backend!

2021-06-03 06:05 UTC, LoicBrassart commented on src/components/Header/Header.jsx
> +    axios.get('http://localhost:8080/images').then(({ data }) => {
Same here

2021-06-03 10:45 UTC, GeorgesFORTRY approved these changes
it's good 😅

2021-06-04 10:46 UTC, LoicBrassart approved these changes
SnE!

2021-06-04 10:58 UTC, merged