Slider
WildCodeSchool/2103-lille-js-p3-edtech-frontend pull request #3
Opened 2021-06-03 07:42 UTC by yulen59

create slider

2021-06-03 09:47 UTC, GeorgesFORTRY requested changes
some bugs to fix

2021-06-03 09:47 UTC, GeorgesFORTRY commented on src/components/Slider/Slider.jsx
> +import PropTypes from 'prop-types';
no need proptypes

2021-06-03 09:47 UTC, GeorgesFORTRY commented on src/components/Slider/Style.jsx
> +
empty line

2021-06-03 09:47 UTC, GeorgesFORTRY commented on src/components/Slider/Style.jsx
> +
empty line

2021-06-03 09:47 UTC, GeorgesFORTRY commented on src/components/Slider/Style.jsx
> +  */
death code

2021-06-03 09:47 UTC, GeorgesFORTRY commented on src/components/Slider/Slider.jsx
> +
you don't need proptypes without props

2021-06-03 10:41 UTC, GeorgesFORTRY submitted a review, later dismissed
ok no more problems

2021-06-04 10:51 UTC, LoicBrassart requested changes
See content

2021-06-04 10:51 UTC, LoicBrassart commented on src/components/Slider/Slider.jsx
> +        </div>
This block could be 66% shorter by using a `slideImages.map()` (and would work with *any* number of slides)

2021-06-04 14:39 UTC, GeorgesFORTRY submitted a review, later dismissed
better 👍

2021-06-07 07:26 UTC, LoicBrassart approved these changes, later dismissed
NmE!

2021-06-07 14:57 UTC, GeorgesFORTRY approved these changes
ok no conflict

2021-06-08 10:59 UTC, LoicBrassart approved these changes
One minor question, but nevermind that's ok!

2021-06-08 10:59 UTC, LoicBrassart commented on .gitignore
> +edTechHdf.vuerd
Why would your vuerd file be in the frontend repo ?

2021-06-08 14:51 UTC, merged