Made relation between the navBar and the accordion thank to the presentation's button
WildCodeSchool/2103-lille-js-p3-edtech-frontend pull request #42
Opened 2021-07-08 10:02 UTC by Hacene010

2021-07-08 10:20 UTC, GeorgesFORTRY requested changes
a little change is needed

2021-07-08 10:20 UTC, GeorgesFORTRY commented on src/components/NavBar/NavBar.jsx
> +      {accordion === true ? <Accordeon /> : null}
no need to put "=== true", just "accordion ?" it's enough

2021-07-08 14:11 UTC, GeorgesFORTRY submitted a review, later dismissed
ok

2021-07-10 07:03 UTC, GeorgesFORTRY submitted a review, later dismissed
ok

2021-07-12 07:33 UTC, LoicBrassart approved these changes, later dismissed
SnE

2021-07-12 07:52 UTC, GeorgesFORTRY submitted a review, later dismissed
ok

2021-07-12 07:57 UTC, LoicBrassart approved these changes, later dismissed
SnE

2021-07-12 08:10 UTC, GeorgesFORTRY approved these changes
ok

2021-07-12 08:14 UTC, LoicBrassart approved these changes
SnE

2021-07-12 08:15 UTC, merged