Members
WildCodeSchool/2103-lille-js-p3-edtech-frontend pull request #7
Opened 2021-06-08 14:48 UTC by GeorgesFORTRY

2021-06-08 18:34 UTC, Hacene010 approved these changes, later dismissed
Think about the VSCode extension ;)

2021-06-09 07:28 UTC, LoicBrassart commented
No validation from the SM, please assign me later!

2021-06-09 07:28 UTC, Hacene010 submitted a review, later dismissed

2021-06-09 07:41 UTC, LoicBrassart requested changes
Clean your .gitignore please

2021-06-09 07:41 UTC, LoicBrassart commented on .gitignore
> +
Useless empty lines

2021-06-09 09:44 UTC, Hacene010 approved these changes
all ok.

2021-06-09 14:02 UTC, LoicBrassart approved these changes
NmE!

2021-06-09 14:08 UTC, merged